from __future__ import annotations

from .cli import LIFECYCLE_EVENTS, build_parser
from .config import load_config
from .constants import CATEGORIES, LIFECYCLE_DEFAULTS, STATUSES, TIERS
from .db import connect
from .doctor import cmd_doctor, get_doctor_checks
from .exports import (
    build_export_artifacts,
    cmd_export,
    refresh_exports,
    write_text,
)
from .helpers import log_action, now_iso, record_exists, row_to_dict, upsert_fts
from .lifecycle import (
    build_lifecycle_counts,
    build_lifecycle_result,
    build_session_paths,
    cmd_lifecycle,
    get_lifecycle_config,
)
from .maintenance import (
    apply_cold_demotions,
    apply_stale_hot_demotions,
    build_audit_tiers_result,
    build_consolidate_result,
    build_hygiene_audit_result,
    cmd_audit_tiers,
    cmd_consolidate,
    cmd_hygiene_audit,
    get_duplicate_groups,
    prune_snapshots,
)
from .oplog import cmd_oplog, get_recent_operations, log_operation
from .paths import CONFIG_PATH, DB_PATH, KB_ROOT, ensure_dirs, memory_path
from .filing_policy import evaluate_filing
from .records import (
    base_record_from_args,
    cmd_bulk_import,
    cmd_create,
    cmd_get,
    cmd_init,
    cmd_list,
    cmd_pending,
    cmd_raw_query,
    cmd_resolve,
    cmd_search,
    cmd_stats,
    cmd_supersede,
    cmd_update,
    fetch_filtered,
    insert_record,
    validate_record,
)
from .schema import ensure_schema
from .sources import (
    build_source_status,
    cmd_analysis_status,
    cmd_ingest,
    cmd_source_content,
    cmd_source_info,
    cmd_source_status,
    cmd_source_update,
    cmd_source_verify,
    cmd_sources,
    cmd_summarize_status,
    compute_file_hash,
    register_source,
    source_exists,
    source_exists_by_hash,
    update_source_record_ids,
    verify_sources,
)
from .wiki import (
    WIKI_DEFAULTS,
    cmd_wiki_check,
    compute_soft_signals,
    compute_wiki_hard_signals,
    compute_wiki_state,
    get_wiki_check_result,
    get_wiki_config,
)
from .wiki_candidates import (
    cmd_wiki_candidates,
    generate_wiki_candidates,
)
from .wiki_materialization import (
    WIKI_CITATION_FENCE,
    WIKI_CITATION_MARKER,
    build_wiki_page,
    capture_snapshot,
    cmd_wiki_lint,
    cmd_wiki_pages,
    cmd_wiki_sync,
    compute_content_hash,
    compute_page_confidence,
    compute_page_id,
    get_db_wiki_checks,
    get_wiki_lint_result,
    is_managed_wiki_file,
    list_wiki_pages,
    mark_stale_pages,
    parse_citation_block,
    persist_page,
    reconcile_wiki_pages,
    sync_wiki,
)

__all__ = [
    "CATEGORIES",
    "CONFIG_PATH",
    "DB_PATH",
    "KB_ROOT",
    "LIFECYCLE_DEFAULTS",
    "LIFECYCLE_EVENTS",
    "STATUSES",
    "TIERS",
    "WIKI_CITATION_FENCE",
    "WIKI_CITATION_MARKER",
    "WIKI_DEFAULTS",
    "apply_cold_demotions",
    "apply_stale_hot_demotions",
    "base_record_from_args",
    "build_audit_tiers_result",
    "build_consolidate_result",
    "build_export_artifacts",
    "build_hygiene_audit_result",
    "build_lifecycle_counts",
    "build_lifecycle_result",
    "build_parser",
    "build_session_paths",
    "build_source_status",
    "build_wiki_page",
    "capture_snapshot",
    "cmd_analysis_status",
    "cmd_audit_tiers",
    "cmd_bulk_import",
    "cmd_consolidate",
    "cmd_create",
    "cmd_doctor",
    "cmd_export",
    "cmd_hygiene_audit",
    "cmd_ingest",
    "cmd_get",
    "cmd_init",
    "cmd_lifecycle",
    "cmd_list",
    "cmd_oplog",
    "cmd_pending",
    "cmd_raw_query",
    "cmd_resolve",
    "cmd_search",
    "cmd_source_content",
    "cmd_source_info",
    "cmd_source_status",
    "cmd_source_update",
    "cmd_source_verify",
    "cmd_sources",
    "cmd_summarize_status",
    "cmd_stats",
    "cmd_supersede",
    "cmd_update",
    "cmd_wiki_candidates",
    "cmd_wiki_check",
    "cmd_wiki_lint",
    "cmd_wiki_pages",
    "cmd_wiki_sync",
    "compute_content_hash",
    "compute_file_hash",
    "compute_page_confidence",
    "compute_page_id",
    "compute_soft_signals",
    "compute_wiki_hard_signals",
    "compute_wiki_state",
    "connect",
    "ensure_dirs",
    "ensure_schema",
    "evaluate_filing",
    "fetch_filtered",
    "generate_wiki_candidates",
    "get_db_wiki_checks",
    "get_doctor_checks",
    "get_duplicate_groups",
    "get_recent_operations",
    "get_lifecycle_config",
    "get_wiki_check_result",
    "get_wiki_config",
    "get_wiki_lint_result",
    "insert_record",
    "is_managed_wiki_file",
    "list_wiki_pages",
    "load_config",
    "log_action",
    "log_operation",
    "mark_stale_pages",
    "memory_path",
    "now_iso",
    "parse_citation_block",
    "persist_page",
    "prune_snapshots",
    "reconcile_wiki_pages",
    "record_exists",
    "refresh_exports",
    "register_source",
    "row_to_dict",
    "source_exists",
    "source_exists_by_hash",
    "sync_wiki",
    "update_source_record_ids",
    "upsert_fts",
    "validate_record",
    "verify_sources",
    "write_text",
]
